<a href="https://colab.research.google.com/github/mauricio5521/data-science/blob/Alura/AluraStoreLatam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Importación de datos

In [2]:
import pandas as pd

url = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_1%20.csv"
url2 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_2.csv"
url3 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_3.csv"
url4 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_4.csv"

tienda = pd.read_csv(url)
tienda2 = pd.read_csv(url2)
tienda3 = pd.read_csv(url3)
tienda4 = pd.read_csv(url4)

tienda.head()

,Producto,Categoría del Producto,Precio,Costo de envío,Fecha de Compra,Vendedor,Lugar de Compra,Calificación,Método de pago,Cantidad de cuotas,lat,lon
0,Asistente virtual,Electrónicos,164300.0,6900.0,16/01/2021,Pedro Gomez,Bogotá,4,Tarjeta de crédito,8,4.60971,-74.08175
1,Mesa de comedor,Muebles,192300.0,8400.0,18/05/2022,Beatriz Morales,Medellín,1,Tarjeta de crédito,4,6.25184,-75.56359
2,Juego de mesa,Juguetes,209600.0,15900.0,15/03/2021,Juan Fernandez,Cartagena,1,Tarjeta de crédito,1,10.39972,-75.51444
3,Microondas,Electrodomésticos,757500.0,41000.0,03/05/2022,Juan Fernandez,Cali,4,Nequi,1,3.43722,-76.52250
4,Silla de oficina,Muebles,335200.0,20200.0,07/11/2020,Maria Alfonso,Medellín,5,Nequi,1,6.25184,-75.56359

In [7]:
# 1. Agregar una columna para identificar cada tienda antes de juntarlas
tienda['Nombre_Tienda'] = 'Tienda 1'
tienda2['Nombre_Tienda'] = 'Tienda 2'
tienda3['Nombre_Tienda'] = 'Tienda 3'
tienda4['Nombre_Tienda'] = 'Tienda 4'

# 2. Unificar (Concatenar) los 4 dataframes en uno solo
df_total = pd.concat([tienda, tienda2, tienda3, tienda4])

# 3. Reiniciar el índice para evitar duplicados en el índice
df_total.reset_index(drop=True, inplace=True)

# Verificamos cómo quedó la tabla maestra
print(f"Total de filas cargadas: {df_total.shape[0]}")
df_total.tail(50)

Total de filas cargadas: 9435

,Producto,Categoría del Producto,Precio,Costo de envío,Fecha de Compra,Vendedor,Lugar de Compra,Calificación,Método de pago,Cantidad de cuotas,lat,lon,Nombre_Tienda
9385,Tablet ABXY,Electrónicos,1752600.0,99200.0,22/03/2021,Santiago Silva,Cali,5,Nequi,1,3.43722,-76.52250,Tienda 4
9386,Armario,Muebles,455400.0,24500.0,09/04/2020,Mariana Herrera,Medellín,3,Nequi,1,6.25184,-75.56359,Tienda 4
9387,Cama box,Muebles,491700.0,24400.0,07/04/2020,Maria Alfonso,Bogotá,1,Tarjeta de crédito,8,4.60971,-74.08175,Tienda 4
9388,Vaso térmico,Deportes y diversión,66600.0,1700.0,10/09/2021,Juliana Costa,Cartagena,4,Tarjeta de crédito,1,10.39972,-75.51444,Tienda 4
9389,Mesa de comedor,Muebles,228000.0,14500.0,29/11/2020,Pedro Gomez,Cali,4,Tarjeta de débito,1,3.43722,-76.52250,Tienda 4
9390,Vaso térmico,Deportes y diversión,28700.0,1900.0,17/01/2021,Mariana Herrera,Bucaramanga,5,Tarjeta de crédito,8,7.12539,-73.11980,Tienda 4
9391,Balón de voleibol,Deportes y diversión,57200.0,8700.0,17/10/2022,Juan Fernandez,Cartagena,5,Tarjeta de crédito,3,10.39972,-75.51444,Tienda 4
9392,Set de vasos,Artículos para el hogar,29800.0,2300.0,20/02/2022,Izabela de León,Bogotá,5,Tarjeta de crédito,7,4.60971,-74.08175,Tienda 4
9393,Carrito de control remoto,Juguetes,67100.0,4000.0,03/03/2021,Beatriz Morales,Bogotá,5,Nequi,1,4.60971,-74.08175,Tienda 4
9394,Guitarra eléctrica,Instrumentos musicales,827200.0,44700.0,25/04/2020,Ángel Rodriguez,Bogotá,5,Tarjeta de crédito,1,4.60971,-74.08175,Tienda 4
9395,Impresora,Electrónicos,266700.0,14900.0,07/01/2022,Izabela de León,Bogotá,4,Tarjeta de crédito,2,4.60971,-74.08175,Tienda 4
9396,Carrito de control remoto,Juguetes,85300.0,9200.0,05/12/2022,Camila Rivera,Bogotá,4,Cupón,1,4.60971,-74.08175,Tienda 4
9397,Asistente virtual,Electrónicos,260100.0,12000.0,13/03/2023,Felipe Santos,Bogotá,5,Nequi,1,4.60971,-74.08175,Tienda 4
9398,Sofá reclinable,Muebles,731300.0,39500.0,29/08/2022,Lucas Olivera,Pereira,5,Tarjeta de crédito,3,4.81333,-75.69611,Tienda 4
9399,Olla de presión,Artículos para el hogar,85600.0,5000.0,05/05/2021,Ángel Rodriguez,Bogotá,5,Tarjeta de crédito,3,4.60971,-74.08175,Tienda 4
9400,Smartwatch,Electrónicos,194100.0,10700.0,18/09/2021,Felipe Santos,Cali,4,Tarjeta de crédito,6,3.43722,-76.52250,Tienda 4
9401,Olla de presión,Artículos para el hogar,70200.0,1900.0,11/05/2020,Beatriz Morales,Cali,4,Tarjeta de crédito,1,3.43722,-76.52250,Tienda 4
9402,Iphone 15,Electrónicos,2519200.0,132300.0,11/09/2020,Pedro Gomez,Pereira,5,Tarjeta de crédito,6,4.81333,-75.69611,Tienda 4
9403,Set de ollas,Artículos para el hogar,103300.0,5900.0,25/04/2022,Blanca Ramirez,Bucaramanga,5,Tarjeta de crédito,6,7.12539,-73.11980,Tienda 4
9404,Cama box,Muebles,649200.0,34800.0,29/03/2021,Santiago Silva,Medellín,4,Nequi,1,6.25184,-75.56359,Tienda 4
9405,Muñeca bebé,Juguetes,39800.0,2500.0,26/03/2022,Camila Rivera,Bogotá,1,Tarjeta de crédito,3,4.60971,-74.08175,Tienda 4
9406,Dinosaurio Rex,Juguetes,17900.0,1500.0,20/06/2021,Maria Alfonso,Bogotá,3,Tarjeta de crédito,2,4.60971,-74.08175,Tienda 4
9407,Ajedrez de madera,Juguetes,33700.0,6600.0,23/06/2020,Blanca Ramirez,Bogotá,5,Nequi,1,4.60971,-74.08175,Tienda 4
9408,Sillón,Muebles,288800.0,15600.0,24/11/2021,Pedro Gomez,Bogotá,5,Tarjeta de crédito,5,4.60971,-74.08175,Tienda 4
9409,Ajedrez de madera,Juguetes,20100.0,1300.0,17/05/2022,Izabela de León,Medellín,4,Tarjeta de crédito,2,6.25184,-75.56359,Tienda 4
9410,Lavavajillas,Electrodomésticos,1340600.0,69600.0,09/02/2022,Izabela de León,Bogotá,1,Tarjeta de crédito,6,4.60971,-74.08175,Tienda 4
9411,Bicicleta,Deportes y diversión,529600.0,26400.0,21/05/2020,Lucas Olivera,Bogotá,4,Nequi,1,4.60971,-74.08175,Tienda 4
9412,Olla de presión,Artículos para el hogar,78100.0,11000.0,20/03/2022,Felipe Santos,Bogotá,5,Tarjeta de crédito,5,4.60971,-74.08175,Tienda 4
9413,TV LED UHD 4K,Electrónicos,2838500.0,149300.0,18/02/2020,Felipe Santos,Medellín,4,Tarjeta de crédito,4,6.25184,-75.56359,Tienda 4
9414,Set de vasos,Artículos para el hogar,32700.0,0.0,09/06/2022,Juliana Costa,Barranquilla,5,Nequi,1,10.96854,-74.78132,Tienda 4
9415,Bloques de construcción,Juguetes,32100.0,0.0,18/02/2022,Lucas Olivera,Bogotá,5,Tarjeta de crédito,2,4.60971,-74.08175,Tienda 4
9416,Estufa,Electrodomésticos,540200.0,27000.0,21/07/2020,Blanca Ramirez,Bogotá,5,Tarjeta de crédito,1,4.60971,-74.08175,Tienda 4
9417,Sillón,Muebles,219800.0,9900.0,03/10/2021,Ángel Rodriguez,Bogotá,5,Nequi,1,4.60971,-74.08175,Tienda 4
9418,Lavavajillas,Electrodomésticos,1358800.0,72600.0,26/04/2022,Rafael Acosta,Bogotá,5,Nequi,1,4.60971,-74.08175,Tienda 4
9419,Balón de voleibol,Deportes y diversión,45100.0,2900.0,25/07/2020,Mariana Herrera,Barranquilla,5,Nequi,1,10.96854,-74.78132,Tienda 4
9420,Sofá reclinable,Muebles,693700.0,35100.0,19/06/2021,Juliana Costa,Cali,4,Nequi,1,3.43722,-76.52250,Tienda 4
9421,Silla de oficina,Muebles,454300.0,24600.0,04/04/2021,Ángel Rodriguez,Santa Marta,1,Tarjeta de crédito,6,11.24079,-74.19904,Tienda 4
9422,Silla de oficina,Muebles,333000.0,18100.0,06/03/2021,Felipe Santos,Leticia,4,Tarjeta de crédito,1,-4.21528,-69.94056,Tienda 4
9423,Lavavajillas,Electrodomésticos,1525100.0,79400.0,23/12/2020,Juan Fernandez,Bogotá,3,Nequi,1,4.60971,-74.08175,Tienda 4
9424,Iniciando en programación,Libros,41800.0,0.0,09/08/2022,Rafael Acosta,Bogotá,5,Cupón,1,4.60971,-74.08175,Tienda 4
9425,Celular ABXY,Electrónicos,799600.0,43300.0,18/07/2020,Beatriz Morales,Bogotá,5,Tarjeta de crédito,1,4.60971,-74.08175,Tienda 4
9426,Mesa de noche,Muebles,256600.0,16000.0,06/01/2022,Juan Fernandez,Barranquilla,5,Tarjeta de crédito,3,10.96854,-74.78132,Tienda 4
9427,Juego de mesa,Juguetes,210800.0,9400.0,16/02/2023,Mariana Herrera,Bogotá,5,Tarjeta de crédito,1,4.60971,-74.08175,Tienda 4
9428,Guitarra acústica,Instrumentos musicales,355000.0,17100.0,30/08/2022,Camila Rivera,Cali,5,Tarjeta de crédito,4,3.43722,-76.52250,Tienda 4
9429,Kit de bancas,Muebles,294400.0,13900.0,09/06/2021,Beatriz Morales,Medellín,1,Tarjeta de crédito,6,6.25184,-75.56359,Tienda 4
9430,Mesa de comedor,Muebles,227700.0,12600.0,12/02/2020,Camila Rivera,Medellín,5,Tarjeta de crédito,1,6.25184,-75.56359,Tienda 4
9431,Silla de oficina,Muebles,342000.0,18600.0,17/05/2022,Felipe Santos,Bucaramanga,5,Tarjeta de crédito,3,7.12539,-73.11980,Tienda 4
9432,Vaso térmico,Deportes y diversión,36700.0,2400.0,03/05/2022,Camila Rivera,Bogotá,5,Tarjeta de crédito,1,4.60971,-74.08175,Tienda 4
9433,Set de ollas,Artículos para el hogar,151800.0,8300.0,15/06/2020,Blanca Ramirez,Cali,5,Tarjeta de crédito,1,3.43722,-76.52250,Tienda 4
9434,Cuerda para saltar,Deportes y diversión,11200.0,1300.0,17/11/2021,Felipe Santos,Bogotá,5,Tarjeta de crédito,1,4.60971,-74.08175,Tienda 4

In [8]:
df_total.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9435 entries, 0 to 9434
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Producto                9435 non-null   object
 1   Categoría del Producto  9435 non-null   object
 2   Precio                  9435 non-null   float64
 3   Costo de envío          9435 non-null   float64
 4   Fecha de Compra         9435 non-null   object
 5   Vendedor                9435 non-null   object
 6   Lugar de Compra         9435 non-null   object
 7   Calificación            9435 non-null   int64
 8   Método de pago          9435 non-null   object
 9   Cantidad de cuotas      9435 non-null   int64
 10  lat                     9435 non-null   float64
 11  lon                     9435 non-null   float64
 12  Nombre_Tienda           9435 non-null   object
dtypes: float64(4), int64(2), object(7)
memory usage: 958.4+ KB

#1. Análisis de facturación

In [10]:
facturacion = (
    df_total
    .groupby('Nombre_Tienda')['Precio']
    .sum()
    .sort_values(ascending=False)
)

print("FACTURACIÓN TOTAL POR TIENDA")
print(facturacion)

FACTURACIÓN TOTAL POR TIENDA
Nombre_Tienda
Tienda 1    1.150880e+09
Tienda 2    1.116344e+09
Tienda 3    1.098020e+09
Tienda 4    1.038376e+09
Name: Precio, dtype: float64

# 2. Ventas por categoría

In [14]:
ventas_categoria = (
    df_total
    .groupby(['Nombre_Tienda', 'Categoría del Producto'])
    .size()
    .reset_index(name='Cantidad_Ventas')
    .sort_values(['Nombre_Tienda', 'Cantidad_Ventas'], ascending=[True, False])
)

print("\nVENTAS POR CATEGORÍA")
print(ventas_categoria)

VENTAS POR CATEGORÍA
   Nombre_Tienda   Categoría del Producto  Cantidad_Ventas
7       Tienda 1                  Muebles              465
3       Tienda 1             Electrónicos              448
5       Tienda 1                 Juguetes              324
2       Tienda 1        Electrodomésticos              312
1       Tienda 1     Deportes y diversión              284
4       Tienda 1   Instrumentos musicales              182
6       Tienda 1                   Libros              173
0       Tienda 1  Artículos para el hogar              171
15      Tienda 2                  Muebles              442
11      Tienda 2             Electrónicos              422
13      Tienda 2                 Juguetes              313
10      Tienda 2        Electrodomésticos              305
9       Tienda 2     Deportes y diversión              275
12      Tienda 2   Instrumentos musicales              224
14      Tienda 2                   Libros              197
8       Tienda 2  Artículos para el hogar              181
23      Tienda 3                  Muebles              499
19      Tienda 3             Electrónicos              451
21      Tienda 3                 Juguetes              315
18      Tienda 3        Electrodomésticos              278
17      Tienda 3     Deportes y diversión              277
22      Tienda 3                   Libros              185
16      Tienda 3  Artículos para el hogar              177
20      Tienda 3   Instrumentos musicales              177
31      Tienda 4                  Muebles              480
27      Tienda 4             Electrónicos              451
29      Tienda 4                 Juguetes              338
25      Tienda 4     Deportes y diversión              277
26      Tienda 4        Electrodomésticos              254
24      Tienda 4  Artículos para el hogar              201
30      Tienda 4                   Libros              187
28      Tienda 4   Instrumentos musicales              170

# 3. Calificación promedio de la tienda

In [16]:
calificacion_promedio = (
    df_total
    .groupby('Nombre_Tienda')['Calificación']
    .mean()
    .sort_values(ascending=False)
)

print("\nCALIFICACIÓN PROMEDIO POR TIENDA")
print(calificacion_promedio)

CALIFICACIÓN PROMEDIO POR TIENDA
Nombre_Tienda
Tienda 3    4.048326
Tienda 2    4.037304
Tienda 4    3.995759
Tienda 1    3.976685
Name: Calificación, dtype: float64

# 4. Productos más y menos vendidos

In [17]:
productos_vendidos = (
    df_total
    .groupby(['Nombre_Tienda', 'Producto'])
    .size()
    .reset_index(name='Cantidad')
)

mas_vendidos = (
    productos_vendidos
    .sort_values(['Nombre_Tienda', 'Cantidad'], ascending=[True, False])
    .groupby('Nombre_Tienda')
    .first()
)

menos_vendidos = (
    productos_vendidos
    .sort_values(['Nombre_Tienda', 'Cantidad'], ascending=[True, True])
    .groupby('Nombre_Tienda')
    .first()
)

print("\nPRODUCTOS MÁS VENDIDOS POR TIENDA")
print(mas_vendidos)

print("\nPRODUCTOS MENOS VENDIDOS POR TIENDA")
print(menos_vendidos)

PRODUCTOS MÁS VENDIDOS POR TIENDA
                                Producto  Cantidad
Nombre_Tienda
Tienda 1                         Armario        60
Tienda 2       Iniciando en programación        65
Tienda 3                   Kit de bancas        57
Tienda 4                        Cama box        62

PRODUCTOS MENOS VENDIDOS POR TIENDA
                                Producto  Cantidad
Nombre_Tienda
Tienda 1       Auriculares con micrófono        33
Tienda 2                   Juego de mesa        32
Tienda 3         Bloques de construcción        35
Tienda 4              Guitarra eléctrica        33

# 5. Envío promedio por tienda

In [20]:
envio_promedio = (
    df_total
    .groupby('Nombre_Tienda')['Costo de envío']
    .mean()
    .sort_values()
)

print("\nCOSTO PROMEDIO DE ENVÍO POR TIENDA")
print(envio_promedio)

COSTO PROMEDIO DE ENVÍO POR TIENDA
Nombre_Tienda
Tienda 4    23459.457167
Tienda 3    24805.680373
Tienda 2    25216.235693
Tienda 1    26018.609580
Name: Costo de envío, dtype: float64

#**Decicsión final**

In [21]:
resumen = pd.DataFrame({
    'Facturacion': facturacion,
    'Calificacion_Promedio': calificacion_promedio,
    'Envio_Promedio': envio_promedio
})

print("\nRESUMEN GENERAL")
print(resumen)

tienda_a_vender = resumen['Facturacion'].idxmin()

print(f"\nRECOMENDACIÓN FINAL:")
print(f"La tienda que presenta el menor desempeño general y debería considerarse para la venta es: {tienda_a_vender}")

RESUMEN GENERAL
                Facturacion  Calificacion_Promedio  Envio_Promedio
Nombre_Tienda
Tienda 1       1.150880e+09               3.976685    26018.609580
Tienda 2       1.116344e+09               4.037304    25216.235693
Tienda 3       1.098020e+09               4.048326    24805.680373
Tienda 4       1.038376e+09               3.995759    23459.457167

RECOMENDACIÓN FINAL:
La tienda que presenta el menor desempeño general y debería considerarse para la venta es: Tienda 4